## This notebook inputs the missing values using Moving Average

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

#### Choose wether the imputation should be done on the data set with daily or weekly granularity

In [2]:
#INPUT, OUTPUT = 'CompleteIndexes.csv','MovingAverageImputed.csv'
INPUT, OUTPUT = 'CompleteWeeklyIndexes', 'MovingAverageWeeklyImputed'

In [3]:
df = pd.read_csv(INPUT+'_training_FE.csv', parse_dates=True, index_col=0)
df_test = pd.read_csv(INPUT+'_test_FE.csv', parse_dates=True, index_col=0)
df.head()

,sp500_Close,sp500_Volume,vix_Close,vix_Volume,dji_Close,dji_Volume,ndx_Close,ndx_Volume,n255_Close,n255_Volume,...,vix_ROC2_13_52,vix_ROC2_13_52_diff1_period3,vix_ROC2_5_26,vix_ROC2_5_26_diff1_period3,vix_ROC2_13_26,vix_ROC2_13_26_diff1_period3,vix_52_Week_High,vix_52_Week_High_diff1_period3,vix_52_Week_Low,vix_52_Week_Low_diff1_period3
2000-01-07,1441.469971,1.225200e+09,21.719999,0.0,11522.559570,184900000.0,3529.600098,1.634930e+09,18193.410156,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN
2000-01-14,1465.150024,1.085900e+09,19.660000,0.0,11722.980469,266830000.0,3704.739990,1.656630e+09,18956.550781,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.099647,NaN,0.000000,NaN
2000-01-21,1441.359985,1.209800e+09,20.820000,0.0,11251.709961,205840000.0,3849.959961,1.923680e+09,18878.089844,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.042319,NaN,0.057328,NaN
2000-01-28,1360.160034,1.095800e+09,26.139999,0.0,10738.870117,183090000.0,3446.129883,1.616370e+09,19434.779297,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.284881,0.284881
2000-02-04,1424.369995,1.045100e+09,21.540001,0.0,10963.799805,166590000.0,3874.370117,1.751450e+09,19763.130859,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.193555,-0.093908,0.091326,0.091326

In [4]:
def imput_moving_average_to_col(df_to_input, num_values):
    for index, row in df_to_input.iterrows():
        if pd.isna(row[0]):
            #print("_______________", row)
            count_prev = 0
            mean = 0
            index_prev = df_to_input.index.get_loc(index)
            while count_prev < num_values:
                index_prev -= 1
                if index_prev < 0:
                    break
                if not pd.isna(df_to_input.iloc[index_prev][0]):
                    count_prev += 1
                    #print(df_to_input.iloc[index_prev])
                    mean += df_to_input.iloc[index_prev]
            count_next = 0
            index_next = df_to_input.index.get_loc(index)
            while count_next < num_values:
                index_next += 1
                if index_next >= len(df_to_input):
                    break
                if not pd.isna(df_to_input.iloc[index_next][0]):
                    count_next += 1
                    #print(df_to_input.iloc[index_next])
                    mean += df_to_input.iloc[index_next]
            mean = mean / (count_prev+count_next)
            #print("MEAN" , mean, "----------------")
            df_to_input.at[index, df_to_input.columns[0]]  = mean
    return df_to_input

In [5]:
for col in df.columns:
    df_imp = imput_moving_average_to_col(df[[col]],1)
    df[col] = df_imp
    print("Column", col, "was imputed.")
df.head()

Column sp500_Close was imputed.
Column sp500_Volume was imputed.
Column vix_Close was imputed.
Column vix_Volume was imputed.
Column dji_Close was imputed.
Column dji_Volume was imputed.
Column ndx_Close was imputed.
Column ndx_Volume was imputed.
Column n255_Close was imputed.
Column n255_Volume was imputed.
Column ftse_Close was imputed.
Column ftse_Volume was imputed.
Column hsi_Close was imputed.
Column hsi_Volume was imputed.
Column n100_Close was imputed.
Column n100_Volume was imputed.
Column Overall EMV Tracker was imputed.
Column infectious_daily_infect_emv_index was imputed.
Column GPR was imputed.
Column trade_US Trade Policy Uncertainty was imputed.
Column trade_Japanese Trade Policy Uncertainty was imputed.
Column trade_Trade Policy EMV Fraction was imputed.
Column sp500_close_ema_5 was imputed.
Column sp500_close_ema_5_diff1_period3 was imputed.
Column sp500_close_ema_5_diff2_period1 was imputed.
Column sp500_close_ema_13 was imputed.
Column sp500_close_ema_13_diff1_period3 was imputed.
Column sp500_close_ema_13_diff2_period1 was imputed.
Column sp500_close_ema_26 was imputed.
Column sp500_close_ema_26_diff1_period3 was imputed.
Column sp500_close_ema_26_diff2_period1 was imputed.
Column sp500_close_ema_52 was imputed.
Column sp500_close_ema_52_diff1_period3 was imputed.
Column sp500_close_ema_52_diff2_period1 was imputed.
Column sp500_log_returns was imputed.
Column sp500_volatility_5 was imputed.
Column sp500_volatility_5_diff1_period3 was imputed.
Column sp500_volatility_5_diff2_period1 was imputed.
Column sp500_volatility_13 was imputed.
Column sp500_volatility_13_diff1_period3 was imputed.
Column sp500_volatility_13_diff2_period1 was imputed.
Column sp500_volatility_26 was imputed.
Column sp500_volatility_26_diff1_period3 was imputed.
Column sp500_volatility_26_diff2_period1 was imputed.
Column sp500_volatility_52 was imputed.
Column sp500_volatility_52_diff1_period3 was imputed.
Column sp500_volatility_52_diff2_period1 was imputed.
Column sp500_skewness_13 was imputed.
Column sp500_skewness_13_diff1_period3 was imputed.
Column sp500_skewness_26 was imputed.
Column sp500_skewness_26_diff1_period3 was imputed.
Column sp500_skewness_52 was imputed.
Column sp500_skewness_52_diff1_period3 was imputed.
Column sp500_kurtosis_13 was imputed.
Column sp500_kurtosis_13_diff1_period3 was imputed.
Column sp500_kurtosis_26 was imputed.
Column sp500_kurtosis_26_diff1_period3 was imputed.
Column sp500_kurtosis_52 was imputed.
Column sp500_kurtosis_52_diff1_period3 was imputed.
Column sp500_obv was imputed.
Column sp500_obv_ema5 was imputed.
Column sp500_obv_ema5_diff1_period3 was imputed.
Column sp500_obv_ema13 was imputed.
Column sp500_obv_ema13_diff1_period3 was imputed.
Column sp500_obv_ema26 was imputed.
Column sp500_obv_ema26_diff1_period3 was imputed.
Column sp500_obv_ema52 was imputed.
Column sp500_obv_ema52_diff1_period3 was imputed.
Column sp500_52_Week_High was imputed.
Column sp500_52_Week_High_diff1_period3 was imputed.
Column sp500_52_Week_Low was imputed.
Column sp500_52_Week_Low_diff1_period3 was imputed.
Column dji_close_ema_5 was imputed.
Column dji_close_ema_5_diff1_period3 was imputed.
Column dji_close_ema_5_diff2_period1 was imputed.
Column dji_close_ema_13 was imputed.
Column dji_close_ema_13_diff1_period3 was imputed.
Column dji_close_ema_13_diff2_period1 was imputed.
Column dji_close_ema_26 was imputed.
Column dji_close_ema_26_diff1_period3 was imputed.
Column dji_close_ema_26_diff2_period1 was imputed.
Column dji_close_ema_52 was imputed.
Column dji_close_ema_52_diff1_period3 was imputed.
Column dji_close_ema_52_diff2_period1 was imputed.
Column dji_log_returns was imputed.
Column dji_volatility_5 was imputed.
Column dji_volatility_5_diff1_period3 was imputed.
Column dji_volatility_5_diff2_period1 was imputed.
Column dji_volatility_13 was imputed.
Column dji_volatility_13_diff1_period3 was imputed.
Column dji_volatility_13_diff2_period1 was imputed.
Column dji_volatility_26 was imputed.
Column dji_volatility_26_diff1_period3 was imputed.
Column dji_volatility_26_diff2_period1 was imputed.
Column dji_volatility_52 was imputed.
Column dji_volatility_52_diff1_period3 was imputed.
Column dji_volatility_52_diff2_period1 was imputed.
Column dji_skewness_13 was imputed.
Column dji_skewness_13_diff1_period3 was imputed.
Column dji_skewness_26 was imputed.
Column dji_skewness_26_diff1_period3 was imputed.
Column dji_skewness_52 was imputed.
Column dji_skewness_52_diff1_period3 was imputed.
Column dji_kurtosis_13 was imputed.
Column dji_kurtosis_13_diff1_period3 was imputed.
Column dji_kurtosis_26 was imputed.
Column dji_kurtosis_26_diff1_period3 was imputed.
Column dji_kurtosis_52 was imputed.
Column dji_kurtosis_52_diff1_period3 was imputed.
Column dji_obv was imputed.
Column dji_obv_ema5 was imputed.
Column dji_obv_ema5_diff1_period3 was imputed.
Column dji_obv_ema13 was imputed.
Column dji_obv_ema13_diff1_period3 was imputed.
Column dji_obv_ema26 was imputed.
Column dji_obv_ema26_diff1_period3 was imputed.
Column dji_obv_ema52 was imputed.
Column dji_obv_ema52_diff1_period3 was imputed.
Column dji_52_Week_High was imputed.
Column dji_52_Week_High_diff1_period3 was imputed.
Column dji_52_Week_Low was imputed.
Column dji_52_Week_Low_diff1_period3 was imputed.
Column ndx_close_ema_5 was imputed.
Column ndx_close_ema_5_diff1_period3 was imputed.
Column ndx_close_ema_5_diff2_period1 was imputed.
Column ndx_close_ema_13 was imputed.
Column ndx_close_ema_13_diff1_period3 was imputed.
Column ndx_close_ema_13_diff2_period1 was imputed.
Column ndx_close_ema_26 was imputed.
Column ndx_close_ema_26_diff1_period3 was imputed.
Column ndx_close_ema_26_diff2_period1 was imputed.
Column ndx_close_ema_52 was imputed.
Column ndx_close_ema_52_diff1_period3 was imputed.
Column ndx_close_ema_52_diff2_period1 was imputed.
Column ndx_log_returns was imputed.
Column ndx_volatility_5 was imputed.
Column ndx_volatility_5_diff1_period3 was imputed.
Column ndx_volatility_5_diff2_period1 was imputed.
Column ndx_volatility_13 was imputed.
Column ndx_volatility_13_diff1_period3 was imputed.
Column ndx_volatility_13_diff2_period1 was imputed.
Column ndx_volatility_26 was imputed.
Column ndx_volatility_26_diff1_period3 was imputed.
Column ndx_volatility_26_diff2_period1 was imputed.
Column ndx_volatility_52 was imputed.
Column ndx_volatility_52_diff1_period3 was imputed.
Column ndx_volatility_52_diff2_period1 was imputed.
Column ndx_skewness_13 was imputed.
Column ndx_skewness_13_diff1_period3 was imputed.
Column ndx_skewness_26 was imputed.
Column ndx_skewness_26_diff1_period3 was imputed.
Column ndx_skewness_52 was imputed.
Column ndx_skewness_52_diff1_period3 was imputed.
Column ndx_kurtosis_13 was imputed.
Column ndx_kurtosis_13_diff1_period3 was imputed.
Column ndx_kurtosis_26 was imputed.
Column ndx_kurtosis_26_diff1_period3 was imputed.
Column ndx_kurtosis_52 was imputed.
Column ndx_kurtosis_52_diff1_period3 was imputed.
Column ndx_obv was imputed.
Column ndx_obv_ema5 was imputed.
Column ndx_obv_ema5_diff1_period3 was imputed.
Column ndx_obv_ema13 was imputed.
Column ndx_obv_ema13_diff1_period3 was imputed.
Column ndx_obv_ema26 was imputed.
Column ndx_obv_ema26_diff1_period3 was imputed.
Column ndx_obv_ema52 was imputed.
Column ndx_obv_ema52_diff1_period3 was imputed.
Column ndx_52_Week_High was imputed.
Column ndx_52_Week_High_diff1_period3 was imputed.
Column ndx_52_Week_Low was imputed.
Column ndx_52_Week_Low_diff1_period3 was imputed.
Column n255_close_ema_5 was imputed.
Column n255_close_ema_5_diff1_period3 was imputed.
Column n255_close_ema_5_diff2_period1 was imputed.
Column n255_close_ema_13 was imputed.
Column n255_close_ema_13_diff1_period3 was imputed.
Column n255_close_ema_13_diff2_period1 was imputed.
Column n255_close_ema_26 was imputed.
Column n255_close_ema_26_diff1_period3 was imputed.
Column n255_close_ema_26_diff2_period1 was imputed.
Column n255_close_ema_52 was imputed.
Column n255_close_ema_52_diff1_period3 was imputed.
Column n255_close_ema_52_diff2_period1 was imputed.
Column n255_log_returns was imputed.
Column n255_volatility_5 was imputed.
Column n255_volatility_5_diff1_period3 was imputed.
Column n255_volatility_5_diff2_period1 was imputed.
Column n255_volatility_13 was imputed.

Column n255_volatility_13_diff1_period3 was imputed.
Column n255_volatility_13_diff2_period1 was imputed.
Column n255_volatility_26 was imputed.
Column n255_volatility_26_diff1_period3 was imputed.
Column n255_volatility_26_diff2_period1 was imputed.
Column n255_volatility_52 was imputed.
Column n255_volatility_52_diff1_period3 was imputed.
Column n255_volatility_52_diff2_period1 was imputed.
Column n255_skewness_13 was imputed.
Column n255_skewness_13_diff1_period3 was imputed.
Column n255_skewness_26 was imputed.
Column n255_skewness_26_diff1_period3 was imputed.
Column n255_skewness_52 was imputed.
Column n255_skewness_52_diff1_period3 was imputed.
Column n255_kurtosis_13 was imputed.
Column n255_kurtosis_13_diff1_period3 was imputed.
Column n255_kurtosis_26 was imputed.
Column n255_kurtosis_26_diff1_period3 was imputed.
Column n255_kurtosis_52 was imputed.
Column n255_kurtosis_52_diff1_period3 was imputed.
Column n255_obv was imputed.
Column n255_obv_ema5 was imputed.
Column n255_obv_ema5_diff1_period3 was imputed.
Column n255_obv_ema13 was imputed.
Column n255_obv_ema13_diff1_period3 was imputed.
Column n255_obv_ema26 was imputed.
Column n255_obv_ema26_diff1_period3 was imputed.
Column n255_obv_ema52 was imputed.
Column n255_obv_ema52_diff1_period3 was imputed.
Column n255_52_Week_High was imputed.
Column n255_52_Week_High_diff1_period3 was imputed.
Column n255_52_Week_Low was imputed.
Column n255_52_Week_Low_diff1_period3 was imputed.
Column ftse_close_ema_5 was imputed.
Column ftse_close_ema_5_diff1_period3 was imputed.
Column ftse_close_ema_5_diff2_period1 was imputed.
Column ftse_close_ema_13 was imputed.
Column ftse_close_ema_13_diff1_period3 was imputed.
Column ftse_close_ema_13_diff2_period1 was imputed.
Column ftse_close_ema_26 was imputed.
Column ftse_close_ema_26_diff1_period3 was imputed.
Column ftse_close_ema_26_diff2_period1 was imputed.
Column ftse_close_ema_52 was imputed.
Column ftse_close_ema_52_diff1_period3 was imputed.
Column ftse_close_ema_52_diff2_period1 was imputed.
Column ftse_log_returns was imputed.
Column ftse_volatility_5 was imputed.
Column ftse_volatility_5_diff1_period3 was imputed.
Column ftse_volatility_5_diff2_period1 was imputed.
Column ftse_volatility_13 was imputed.
Column ftse_volatility_13_diff1_period3 was imputed.
Column ftse_volatility_13_diff2_period1 was imputed.
Column ftse_volatility_26 was imputed.
Column ftse_volatility_26_diff1_period3 was imputed.
Column ftse_volatility_26_diff2_period1 was imputed.
Column ftse_volatility_52 was imputed.
Column ftse_volatility_52_diff1_period3 was imputed.
Column ftse_volatility_52_diff2_period1 was imputed.
Column ftse_skewness_13 was imputed.
Column ftse_skewness_13_diff1_period3 was imputed.
Column ftse_skewness_26 was imputed.
Column ftse_skewness_26_diff1_period3 was imputed.
Column ftse_skewness_52 was imputed.
Column ftse_skewness_52_diff1_period3 was imputed.
Column ftse_kurtosis_13 was imputed.
Column ftse_kurtosis_13_diff1_period3 was imputed.
Column ftse_kurtosis_26 was imputed.
Column ftse_kurtosis_26_diff1_period3 was imputed.
Column ftse_kurtosis_52 was imputed.
Column ftse_kurtosis_52_diff1_period3 was imputed.
Column ftse_obv was imputed.
Column ftse_obv_ema5 was imputed.
Column ftse_obv_ema5_diff1_period3 was imputed.
Column ftse_obv_ema13 was imputed.
Column ftse_obv_ema13_diff1_period3 was imputed.
Column ftse_obv_ema26 was imputed.
Column ftse_obv_ema26_diff1_period3 was imputed.
Column ftse_obv_ema52 was imputed.
Column ftse_obv_ema52_diff1_period3 was imputed.
Column ftse_52_Week_High was imputed.
Column ftse_52_Week_High_diff1_period3 was imputed.
Column ftse_52_Week_Low was imputed.
Column ftse_52_Week_Low_diff1_period3 was imputed.
Column hsi_close_ema_5 was imputed.
Column hsi_close_ema_5_diff1_period3 was imputed.
Column hsi_close_ema_5_diff2_period1 was imputed.
Column hsi_close_ema_13 was imputed.
Column hsi_close_ema_13_diff1_period3 was imputed.
Column hsi_close_ema_13_diff2_period1 was imputed.
Column hsi_close_ema_26 was imputed.
Column hsi_close_ema_26_diff1_period3 was imputed.
Column hsi_close_ema_26_diff2_period1 was imputed.
Column hsi_close_ema_52 was imputed.
Column hsi_close_ema_52_diff1_period3 was imputed.
Column hsi_close_ema_52_diff2_period1 was imputed.
Column hsi_log_returns was imputed.
Column hsi_volatility_5 was imputed.
Column hsi_volatility_5_diff1_period3 was imputed.
Column hsi_volatility_5_diff2_period1 was imputed.
Column hsi_volatility_13 was imputed.
Column hsi_volatility_13_diff1_period3 was imputed.
Column hsi_volatility_13_diff2_period1 was imputed.
Column hsi_volatility_26 was imputed.
Column hsi_volatility_26_diff1_period3 was imputed.
Column hsi_volatility_26_diff2_period1 was imputed.
Column hsi_volatility_52 was imputed.
Column hsi_volatility_52_diff1_period3 was imputed.
Column hsi_volatility_52_diff2_period1 was imputed.
Column hsi_skewness_13 was imputed.
Column hsi_skewness_13_diff1_period3 was imputed.
Column hsi_skewness_26 was imputed.
Column hsi_skewness_26_diff1_period3 was imputed.
Column hsi_skewness_52 was imputed.
Column hsi_skewness_52_diff1_period3 was imputed.
Column hsi_kurtosis_13 was imputed.
Column hsi_kurtosis_13_diff1_period3 was imputed.
Column hsi_kurtosis_26 was imputed.
Column hsi_kurtosis_26_diff1_period3 was imputed.
Column hsi_kurtosis_52 was imputed.
Column hsi_kurtosis_52_diff1_period3 was imputed.
Column hsi_obv was imputed.
Column hsi_obv_ema5 was imputed.
Column hsi_obv_ema5_diff1_period3 was imputed.
Column hsi_obv_ema13 was imputed.
Column hsi_obv_ema13_diff1_period3 was imputed.
Column hsi_obv_ema26 was imputed.
Column hsi_obv_ema26_diff1_period3 was imputed.
Column hsi_obv_ema52 was imputed.
Column hsi_obv_ema52_diff1_period3 was imputed.
Column hsi_52_Week_High was imputed.
Column hsi_52_Week_High_diff1_period3 was imputed.
Column hsi_52_Week_Low was imputed.
Column hsi_52_Week_Low_diff1_period3 was imputed.
Column n100_close_ema_5 was imputed.
Column n100_close_ema_5_diff1_period3 was imputed.
Column n100_close_ema_5_diff2_period1 was imputed.
Column n100_close_ema_13 was imputed.
Column n100_close_ema_13_diff1_period3 was imputed.
Column n100_close_ema_13_diff2_period1 was imputed.
Column n100_close_ema_26 was imputed.
Column n100_close_ema_26_diff1_period3 was imputed.
Column n100_close_ema_26_diff2_period1 was imputed.
Column n100_close_ema_52 was imputed.
Column n100_close_ema_52_diff1_period3 was imputed.
Column n100_close_ema_52_diff2_period1 was imputed.
Column n100_log_returns was imputed.
Column n100_volatility_5 was imputed.
Column n100_volatility_5_diff1_period3 was imputed.
Column n100_volatility_5_diff2_period1 was imputed.
Column n100_volatility_13 was imputed.
Column n100_volatility_13_diff1_period3 was imputed.
Column n100_volatility_13_diff2_period1 was imputed.
Column n100_volatility_26 was imputed.
Column n100_volatility_26_diff1_period3 was imputed.
Column n100_volatility_26_diff2_period1 was imputed.
Column n100_volatility_52 was imputed.
Column n100_volatility_52_diff1_period3 was imputed.
Column n100_volatility_52_diff2_period1 was imputed.
Column n100_skewness_13 was imputed.
Column n100_skewness_13_diff1_period3 was imputed.
Column n100_skewness_26 was imputed.
Column n100_skewness_26_diff1_period3 was imputed.
Column n100_skewness_52 was imputed.
Column n100_skewness_52_diff1_period3 was imputed.
Column n100_kurtosis_13 was imputed.
Column n100_kurtosis_13_diff1_period3 was imputed.
Column n100_kurtosis_26 was imputed.
Column n100_kurtosis_26_diff1_period3 was imputed.
Column n100_kurtosis_52 was imputed.
Column n100_kurtosis_52_diff1_period3 was imputed.
Column n100_obv was imputed.
Column n100_obv_ema5 was imputed.
Column n100_obv_ema5_diff1_period3 was imputed.
Column n100_obv_ema13 was imputed.
Column n100_obv_ema13_diff1_period3 was imputed.
Column n100_obv_ema26 was imputed.
Column n100_obv_ema26_diff1_period3 was imputed.
Column n100_obv_ema52 was imputed.
Column n100_obv_ema52_diff1_period3 was imputed.
Column n100_52_Week_High was imputed.
Column n100_52_Week_High_diff1_period3 was imputed.
Column n100_52_Week_Low was imputed.
Column n100_52_Week_Low_diff1_period3 was imputed.
Column vix_close_ema_5 was imputed.

Column vix_close_ema_5_diff1_period3 was imputed.
Column vix_close_ema_5_diff2_period1 was imputed.
Column vix_close_ema_13 was imputed.
Column vix_close_ema_13_diff1_period3 was imputed.
Column vix_close_ema_13_diff2_period1 was imputed.
Column vix_close_ema_26 was imputed.
Column vix_close_ema_26_diff1_period3 was imputed.
Column vix_close_ema_26_diff2_period1 was imputed.
Column vix_close_ema_52 was imputed.
Column vix_close_ema_52_diff1_period3 was imputed.
Column vix_close_ema_52_diff2_period1 was imputed.
Column vix_skewness_5 was imputed.
Column vix_skewness_13 was imputed.
Column vix_skewness_26 was imputed.
Column vix_skewness_52 was imputed.
Column vix_kurtosis_5 was imputed.
Column vix_kurtosis_13 was imputed.
Column vix_kurtosis_26 was imputed.
Column vix_kurtosis_52 was imputed.
Column vix_ROC_5_52 was imputed.
Column vix_ROC_5_52_diff1_period3 was imputed.
Column vix_ROC_13_52 was imputed.
Column vix_ROC_13_52_diff1_period3 was imputed.
Column vix_ROC_5_26 was imputed.
Column vix_ROC_5_26_diff1_period3 was imputed.
Column vix_ROC_13_26 was imputed.
Column vix_ROC_13_26_diff1_period3 was imputed.
Column vix_ROC2_5_52 was imputed.
Column vix_ROC2_5_52_diff1_period3 was imputed.
Column vix_ROC2_13_52 was imputed.
Column vix_ROC2_13_52_diff1_period3 was imputed.
Column vix_ROC2_5_26 was imputed.
Column vix_ROC2_5_26_diff1_period3 was imputed.
Column vix_ROC2_13_26 was imputed.
Column vix_ROC2_13_26_diff1_period3 was imputed.
Column vix_52_Week_High was imputed.
Column vix_52_Week_High_diff1_period3 was imputed.
Column vix_52_Week_Low was imputed.
Column vix_52_Week_Low_diff1_period3 was imputed.

,sp500_Close,sp500_Volume,vix_Close,vix_Volume,dji_Close,dji_Volume,ndx_Close,ndx_Volume,n255_Close,n255_Volume,...,vix_ROC2_13_52,vix_ROC2_13_52_diff1_period3,vix_ROC2_5_26,vix_ROC2_5_26_diff1_period3,vix_ROC2_13_26,vix_ROC2_13_26_diff1_period3,vix_52_Week_High,vix_52_Week_High_diff1_period3,vix_52_Week_Low,vix_52_Week_Low_diff1_period3
2000-01-07,1441.469971,1.225200e+09,21.719999,0.0,11522.559570,184900000.0,3529.600098,1.634930e+09,18193.410156,0.0,...,0.0,12.038711,0.0,12.038711,0.0,12.038711,0.000000,0.000000,0.000000,0.284881
2000-01-14,1465.150024,1.085900e+09,19.660000,0.0,11722.980469,266830000.0,3704.739990,1.656630e+09,18956.550781,0.0,...,0.0,12.038711,0.0,12.038711,0.0,12.038711,-0.099647,0.000000,0.000000,0.284881
2000-01-21,1441.359985,1.209800e+09,20.820000,0.0,11251.709961,205840000.0,3849.959961,1.923680e+09,18878.089844,0.0,...,0.0,12.038711,0.0,12.038711,0.0,12.038711,-0.042319,0.000000,0.057328,0.284881
2000-01-28,1360.160034,1.095800e+09,26.139999,0.0,10738.870117,183090000.0,3446.129883,1.616370e+09,19434.779297,0.0,...,0.0,12.038711,0.0,12.038711,0.0,12.038711,0.000000,0.000000,0.284881,0.284881
2000-02-04,1424.369995,1.045100e+09,21.540001,0.0,10963.799805,166590000.0,3874.370117,1.751450e+09,19763.130859,0.0,...,0.0,12.038711,0.0,12.038711,0.0,12.038711,-0.193555,-0.093908,0.091326,0.091326

In [6]:
df.to_csv(OUTPUT+'_training_FE.csv', index = True)
df_final = df

### Imputing Test Data

In [7]:
df = df_final
df.tail()

,sp500_Close,sp500_Volume,vix_Close,vix_Volume,dji_Close,dji_Volume,ndx_Close,ndx_Volume,n255_Close,n255_Volume,...,vix_ROC2_13_52,vix_ROC2_13_52_diff1_period3,vix_ROC2_5_26,vix_ROC2_5_26_diff1_period3,vix_ROC2_13_26,vix_ROC2_13_26_diff1_period3,vix_52_Week_High,vix_52_Week_High_diff1_period3,vix_52_Week_Low,vix_52_Week_Low_diff1_period3
2014-11-28,2067.560059,2.504640e+09,13.33,0.0,17828.240234,80470000.0,4337.790039,9.986000e+08,17459.849609,149100.0,...,-64.966242,2.640466,-64.966242,2.640466,-64.966242,2.640466,-0.500571,0.015879,0.216974,0.015879
2014-12-05,2075.370117,3.419620e+09,11.89,0.0,17958.789063,79110000.0,4311.569824,1.767100e+09,17920.449219,128900.0,...,-84.945332,-19.731207,-84.945332,-19.731207,-84.945332,-19.731207,-0.614890,-0.112818,0.102654,-0.112818
2014-12-12,2002.329956,4.157650e+09,21.08,0.0,17280.830078,121950000.0,4199.279785,1.888870e+09,17371.580078,214500.0,...,77.291842,147.756958,77.291842,147.756958,77.291842,147.756958,-0.042263,0.491097,0.675281,0.491097
2014-12-19,2070.649902,6.465530e+09,16.49,0.0,17804.800781,343690000.0,4281.779785,3.287920e+09,17621.400391,175800.0,...,38.687973,103.654215,38.687973,103.654215,38.687973,103.654215,-0.287834,0.212737,0.429711,0.212737
2014-12-26,2088.770020,1.735230e+09,14.50,0.0,18053.710938,52570000.0,4314.089844,9.302200e+08,17818.960938,86500.0,...,-51.655172,33.290160,38.687973,103.654215,38.687973,103.654215,-0.416439,0.198451,0.301105,0.198451

In [8]:
def imput_moving_average_to_col_test(df_to_input, num_values):
    if(pd.isna(df_to_input.iloc[-1,0])):
        mean = np.sum(df_to_input.iloc[(-num_values-1):-2,0]) / (num_values)
        df_to_input.at[df_to_input.index[-1], df_to_input.columns[0]] = mean
    return df_to_input

In [9]:
df_test.head()

,sp500_Close,sp500_Volume,vix_Close,vix_Volume,dji_Close,dji_Volume,ndx_Close,ndx_Volume,n255_Close,n255_Volume,...,vix_ROC2_13_52,vix_ROC2_13_52_diff1_period3,vix_ROC2_5_26,vix_ROC2_5_26_diff1_period3,vix_ROC2_13_26,vix_ROC2_13_26_diff1_period3,vix_52_Week_High,vix_52_Week_High_diff1_period3,vix_52_Week_Low,vix_52_Week_Low_diff1_period3
2015-01-02,2058.199951,2.708700e+09,17.790001,0.0,17832.990234,76270000.0,4230.240234,1.435150e+09,NaN,NaN,...,49.621539,-27.670303,49.621539,-27.670303,49.621539,-27.670303,-0.211951,-0.169688,0.505593,-0.169688
2015-01-09,2044.810059,3.364140e+09,17.549999,0.0,17737.369141,93390000.0,4213.279785,1.715830e+09,17197.730469,155200.0,...,47.603019,8.915046,-25.299152,-63.987126,47.603019,8.915046,-0.225534,0.062300,0.492010,0.062300
2015-01-16,2019.420044,4.056410e+09,20.950001,0.0,17511.570313,140480000.0,4142.140137,1.970520e+09,16864.160156,171100.0,...,76.198495,127.853667,44.482766,NaN,76.198495,NaN,-0.048449,0.367990,0.669095,0.367990
2015-01-23,2051.820068,3.573560e+09,16.660000,0.0,17672.599609,97110000.0,4278.140137,1.653830e+09,17511.750000,132500.0,...,40.117746,-9.503793,-31.992797,-81.614336,40.117746,-9.503793,-0.277577,-0.065626,0.439967,-0.065626
2015-01-30,1994.989990,4.568650e+09,20.969999,0.0,17164.949219,168560000.0,4148.430176,2.264230e+09,17674.390625,173500.0,...,76.366686,28.763667,25.870342,51.169495,76.366686,28.763667,-0.047495,0.178039,0.670049,0.178039

In [10]:
for index, row in df_test.iterrows():
    indexes = [index]
    new_df = pd.DataFrame(data=row, index=indexes, columns=df_test.columns)
    df = pd.concat([df,new_df])

    for col in df.columns:
        df_imp = imput_moving_average_to_col_test(df[[col]],2)
        df[col] = df_imp

In [11]:
df = df.loc['2015-01-02':]
df.to_csv(OUTPUT+ '_test_FE.csv', index = True)