In [1]:
import pandas as pd
from datetime import datetime

In [2]:
#Daily
v_sp500 = pd.read_csv('S&P500.csv', parse_dates=True)
v_sp500['Date'] = pd.to_datetime(v_sp500['Date'], infer_datetime_format=True)
v_sp500.index = v_sp500['Date'].values
v_sp500 = v_sp500.loc['2000-01-01':'2020-03-18']
v_sp500 = v_sp500.drop(['Date', 'Adj Close'], axis=1)
v_sp500 = v_sp500.add_prefix('sp500_')
v_sp500.tail()

             sp500_Open   sp500_High    sp500_Low  sp500_Close  sp500_Volume
2020-03-12  2630.860107  2660.949951  2478.860107  2480.639893    8829380000
2020-03-13  2569.989990  2711.330078  2492.370117  2711.020020    8258670000
2020-03-16  2508.590088  2562.979980  2380.939941  2386.129883    7781540000
2020-03-17  2425.659912  2553.929932  2367.040039  2529.189941    8358500000
2020-03-18  2436.500000  2453.570068  2280.520020  2398.100098    8755780000

In [3]:
#Daily
v_vix = pd.read_csv('VIX.csv', parse_dates=True)
v_vix['Date'] = pd.to_datetime(v_vix['Date'], infer_datetime_format=True)
v_vix.index = v_vix['Date'].values
v_vix = v_vix.loc['2000-01-01':'2020-03-18']
v_vix = v_vix.drop(['Date', 'Adj Close'], axis=1)
v_vix = v_vix.add_prefix('vix_')
v_vix.head()

             vix_Open   vix_High    vix_Low  vix_Close  vix_Volume
2000-01-03  24.360001  26.150000  23.980000  24.209999           0
2000-01-04  24.940001  27.180000  24.799999  27.010000           0
2000-01-05  27.980000  29.000000  25.850000  26.410000           0
2000-01-06  26.680000  26.709999  24.700001  25.730000           0
2000-01-07  25.139999  25.170000  21.719999  21.719999           0

In [4]:
#Daily
v_dji = pd.read_csv('^DJI.csv', parse_dates=True)
v_dji['Date'] = pd.to_datetime(v_dji['Date'], infer_datetime_format=True)
v_dji.index = v_dji['Date'].values
v_dji = v_dji.loc['2000-01-01':'2020-03-18']
v_dji = v_dji.drop(['Date', 'Adj Close'], axis=1)
v_dji = v_dji.add_prefix('dji_')
v_dji.head()

                dji_Open      dji_High       dji_Low     dji_Close  dji_Volume
2000-01-03  11501.849609  11522.009766  11305.690430  11357.509766   169750000
2000-01-04  11349.750000  11350.059570  10986.450195  10997.929688   178420000
2000-01-05  10989.370117  11215.099609  10938.669922  11122.650391   203190000
2000-01-06  11113.370117  11313.450195  11098.450195  11253.259766   176550000
2000-01-07  11247.059570  11528.139648  11239.919922  11522.559570   184900000

In [5]:
#Daily
v_ndx = pd.read_csv('^NDX.csv', parse_dates=True)
v_ndx['Date'] = pd.to_datetime(v_ndx['Date'], infer_datetime_format=True)
v_ndx.index = v_ndx['Date'].values
v_ndx = v_ndx.loc['2000-01-01':'2020-03-18']
v_ndx = v_ndx.drop(['Date', 'Adj Close'], axis=1)
v_ndx = v_ndx.add_prefix('ndx_')
v_ndx.head()

               ndx_Open     ndx_High     ndx_Low    ndx_Close  ndx_Volume
2000-01-03  3755.739990  3836.860107  3643.25000  3790.550049  1510070000
2000-01-04  3766.570068  3766.570068  3542.72998  3546.199951  1511840000
2000-01-05  3543.129883  3576.169922  3371.75000  3507.310059  1735670000
2000-01-06  3488.310059  3513.550049  3334.02002  3340.810059  1598320000
2000-01-07  3337.260010  3529.750000  3314.75000  3529.600098  1634930000

In [6]:
#Daily
v_n225 = pd.read_csv('N225.csv', parse_dates=True)
v_n225['Date'] = pd.to_datetime(v_n225['Date'], infer_datetime_format=True)
v_n225.index = v_n225['Date'].values
v_n225 = v_n225.loc['2000-01-01':'2020-03-18']
v_n225 = v_n225.drop(['Date', 'Adj Close'], axis=1)
v_n225 = v_n225.add_prefix('n255_')
v_n225.head()

,n255_Open,n255_High,n255_Low,n255_Close,n255_Volume
2000-01-04,18937.449219,19187.609375,18937.449219,19002.859375,0.0
2000-01-05,19003.509766,19003.509766,18221.820313,18542.550781,0.0
2000-01-06,18574.009766,18582.740234,18168.269531,18168.269531,0.0
2000-01-07,18194.050781,18285.730469,18068.099609,18193.410156,0.0
2000-01-10,NaN,NaN,NaN,NaN,NaN

In [7]:
#Daily
v_ftse = pd.read_csv('CompleteFTSE.csv', parse_dates=True)
v_ftse['Date'] = pd.to_datetime(v_ftse['Date'], infer_datetime_format=True)
v_ftse.index = v_ftse['Date'].values
v_ftse = v_ftse.loc['2000-01-01':'2020-03-18']
v_ftse = v_ftse.drop(['Date', 'Adj Close'], axis=1)
v_ftse = v_ftse.add_prefix('ftse_')
v_ftse.head()

              ftse_Open    ftse_High     ftse_Low   ftse_Close  ftse_Volume
2000-01-03          NaN          NaN          NaN          NaN          NaN
2000-01-04  6930.200195  6930.200195  6662.899902  6665.899902  633449000.0
2000-01-05  6665.899902  6665.899902  6500.399902  6535.899902  670234000.0
2000-01-06  6535.899902  6547.299805  6424.399902  6447.200195  785532000.0
2000-01-07  6447.200195  6532.399902  6438.799805  6504.799805  888306000.0

In [8]:
#Daily
v_hsi = pd.read_csv('^HSI.csv', parse_dates=True)
v_hsi['Date'] = pd.to_datetime(v_hsi['Date'], infer_datetime_format=True)
v_hsi.index = v_hsi['Date'].values
v_hsi = v_hsi.loc['2000-01-01':'2020-03-18']
v_hsi = v_hsi.drop(['Date', 'Adj Close'], axis=1)
v_hsi = v_hsi.add_prefix('hsi_')
v_hsi.head()

                hsi_Open      hsi_High       hsi_Low     hsi_Close  hsi_Volume
2000-01-03  17057.699219  17426.160156  17057.699219  17369.630859         0.0
2000-01-04  17303.000000  17303.000000  16933.519531  17072.820313         0.0
2000-01-05  16608.550781  16608.550781  15688.490234  15846.719727         0.0
2000-01-06  15942.070313  15971.030273  14763.969727  15153.230469         0.0
2000-01-07  15329.339844  15513.889648  15108.750000  15405.629883         0.0

In [9]:
#Daily
v_n100 = pd.read_csv('^N100.csv', parse_dates=True)
v_n100['Date'] = pd.to_datetime(v_n100['Date'], infer_datetime_format=True)
v_n100.index = v_n100['Date'].values
v_n100 = v_n100.loc['2000-01-01':'2020-03-18']
v_n100 = v_n100.drop(['Date', 'Adj Close'], axis=1)
v_n100 = v_n100.add_prefix('n100_')
v_n100.head()

             n100_Open   n100_High    n100_Low  n100_Close  n100_Volume
2000-01-03  996.770020  996.770020  996.770020  996.770020          0.0
2000-01-04  955.969971  955.969971  955.969971  955.969971          0.0
2000-01-05  930.260010  930.260010  930.260010  930.260010          0.0
2000-01-06  922.460022  922.460022  922.460022  922.460022          0.0
2000-01-07  943.880005  943.880005  943.880005  943.880005          0.0

In [10]:
#Monthly
v_emv =  pd.read_excel('EMV_Data.xlsx') 
Date = v_emv.apply(lambda x: datetime(int(x['Year']),int(x['Month']),28), axis=1)
v_emv['Date'] = Date
v_emv['Date'] = pd.to_datetime(v_emv['Date'], infer_datetime_format=True)
v_emv.index = v_emv['Date'].values
v_emv = v_emv.loc['2000-01-01':'2020-03-18']
v_emv = v_emv[['Overall EMV Tracker']]
v_emv.head()

            Overall EMV Tracker
2000-01-28            24.412899
2000-02-28            19.913437
2000-03-28            26.104673
2000-04-28            43.429073
2000-05-28            34.308361

In [11]:
#Daily
v_infectious = pd.read_csv('All_Infectious_EMV_Data.csv')
Date = v_infectious.apply(lambda x: datetime(int(x['year']),int(x['month']), int(x['day'])), axis=1)
v_infectious['Date'] = Date
v_infectious['Date'] = pd.to_datetime(v_infectious['Date'], infer_datetime_format=True)
v_infectious.index = v_infectious['Date'].values
v_infectious = v_infectious.loc['2000-01-01':'2020-03-18']
v_infectious = v_infectious.drop(['Date', 'day', 'month', 'year'], axis=1)
v_infectious = v_infectious.add_prefix('infectious_')
v_infectious.head()

            infectious_daily_infect_emv_index
2000-01-01                               1.05
2000-01-02                               2.62
2000-01-03                               0.00
2000-01-04                               0.99
2000-01-05                               0.00

In [12]:
#Quarterly - might not use
v_financial_stress = pd.read_excel('Financial_Stress.xlsx')
Date = v_financial_stress.apply(lambda x: datetime(int(x['year']),int(x['quarter'])*3, 28), axis=1)
v_financial_stress['Date'] = Date
v_financial_stress['Date'] = pd.to_datetime(v_financial_stress['Date'], infer_datetime_format=True)
v_financial_stress.index = v_financial_stress['Date'].values
v_financial_stress = v_financial_stress.loc['2000-01-01':'2020-03-18']
v_financial_stress = v_financial_stress.drop(['date', 'Date', 'quarter', 'year'], axis=1)
v_financial_stress = v_financial_stress.add_prefix('financial_')
v_financial_stress.head()

            financial_indicator
2000-03-28           101.588292
2000-06-28           101.361929
2000-09-28           100.836200
2000-12-28           101.377272
2001-03-28           102.227537

In [13]:
#Monthly
v_gpr = pd.read_excel('gpr_web_latest.xlsx')
v_gpr['Date'] = pd.to_datetime(v_gpr['Date'], infer_datetime_format=True)
v_gpr.index = v_gpr['Date'].values
v_gpr = v_gpr.loc['2000-01-01':'2020-03-18']
v_gpr = v_gpr[['GPR']]
v_gpr.head()

                  GPR
2000-01-01  40.634806
2000-02-01  34.391162
2000-03-01  54.098793
2000-04-01  35.769024
2000-05-01  34.094887

In [14]:
#Monthly
v_trade_uncertainty = pd.read_excel('Trade_Uncertainty_Data.xlsx') 
Date = v_trade_uncertainty.apply(lambda x: datetime(int(x['Year']),int(x['Month']),28), axis=1)
v_trade_uncertainty['Date'] = Date
v_trade_uncertainty['Date'] = pd.to_datetime(v_trade_uncertainty['Date'], infer_datetime_format=True)
v_trade_uncertainty.index = v_trade_uncertainty['Date'].values
v_trade_uncertainty = v_trade_uncertainty.loc['2000-01-01':'2020-03-18']
v_trade_uncertainty = v_trade_uncertainty.drop(['Date', 'Year', 'Month'], axis=1)
v_trade_uncertainty = v_trade_uncertainty.add_prefix('trade_')
v_trade_uncertainty.head()

,trade_US Trade Policy Uncertainty,trade_Japanese Trade Policy Uncertainty,trade_Trade Policy EMV Fraction
2000-01-28,71.914247,117.577146,0.033573
2000-02-28,50.352413,58.499365,0.026471
2000-03-28,88.179754,31.808480,0.028139
2000-04-28,82.574216,54.061788,0.033755
2000-05-28,245.009584,73.961645,0.025000

In [15]:
#Daily, but missing 11 years of data. Might not use
v_twitter = pd.read_excel('Twitter_Uncertainty.xlsx') 
v_twitter['date'] = pd.to_datetime(v_twitter['date'], infer_datetime_format=True)
v_twitter.index = v_twitter['date'].values
v_twitter = v_twitter.loc['2000-01-01':'2020-03-18']
v_twitter = v_twitter.drop(['date'], axis=1)
v_twitter = v_twitter.add_prefix('twitter_')
v_twitter.head()

            twitter_TEU  twitter_TMU
2011-01-01    25.234161    18.629798
2011-01-02    35.327825    17.299098
2011-01-03    50.468322    42.582395
2011-01-04    47.103767    62.542893
2011-01-05    30.280993    46.574495

In [16]:
#Quarterly. Might not use
v_wui_index = pd.read_excel('WUI_Data-1.xlsx')

In [17]:
df = pd.concat([v_sp500, v_vix, v_dji, v_ndx, v_n225, v_ftse, v_hsi, v_n100, v_emv, v_infectious, v_gpr, v_trade_uncertainty], axis=1, join='outer')

In [18]:
at_least_one_value_missing = df.apply(lambda x: (len(x)-x.count())>=1, axis=1)

In [19]:
at_least_one_value_missing.value_counts()

True    7383
dtype: int64

In [20]:
df

,sp500_Open,sp500_High,sp500_Low,sp500_Close,sp500_Volume,vix_Open,vix_High,vix_Low,vix_Close,vix_Volume,...,n100_High,n100_Low,n100_Close,n100_Volume,Overall EMV Tracker,infectious_daily_infect_emv_index,GPR,trade_US Trade Policy Uncertainty,trade_Japanese Trade Policy Uncertainty,trade_Trade Policy EMV Fraction
2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.05,40.634806,NaN,NaN,NaN
2000-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.62,NaN,NaN,NaN,NaN
2000-01-03,1469.250000,1478.000000,1438.359985,1455.219971,9.318000e+08,24.360001,26.150000,23.980000,24.209999,0.0,...,996.770020,996.770020,996.770020,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1.009000e+09,24.940001,27.180000,24.799999,27.010000,0.0,...,955.969971,955.969971,955.969971,0.0,NaN,0.99,NaN,NaN,NaN,NaN
2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1.085500e+09,27.980000,29.000000,25.850000,26.410000,0.0,...,930.260010,930.260010,930.260010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1.092300e+09,26.680000,26.709999,24.700001,25.730000,0.0,...,922.460022,922.460022,922.460022,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1.225200e+09,25.139999,25.170000,21.719999,21.719999,0.0,...,943.880005,943.880005,943.880005,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1.064800e+09,21.889999,22.490000,21.360001,21.709999,0.0,...,960.219971,960.219971,960.219971,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-11,1457.599976,1458.660034,1434.420044,1438.560059,1.014000e+09,21.980000,22.629999,21.690001,22.500000,0.0,...,954.059998,954.059998,954.059998,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-12,1438.560059,1442.599976,1427.079956,1432.250000,9.746000e+08,23.049999,23.490000,22.410000,22.840000,0.0,...,946.830017,946.830017,946.830017,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-13,1432.250000,1454.199951,1432.250000,1449.680054,1.030400e+09,22.730000,23.100000,21.320000,21.709999,0.0,...,951.820007,951.820007,951.820007,0.0,NaN,0.72,NaN,NaN,NaN,NaN
2000-01-14,1449.680054,1473.000000,1449.680054,1465.150024,1.085900e+09,19.830000,20.150000,19.510000,19.660000,0.0,...,973.859985,973.859985,973.859985,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,979.960022,979.960022,979.960022,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-18,1465.150024,1465.150024,1451.300049,1455.140015,1.056700e+09,21.389999,21.629999,20.969999,21.500000,0.0,...,952.590027,952.590027,952.590027,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-19,1455.140015,1461.390015,1448.680054,1455.900024,1.087800e+09,22.150000,22.160000,21.440001,21.719999,0.0,...,951.260010,951.260010,951.260010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-20,1455.900024,1465.709961,1438.540039,1445.569946,1.100700e+09,21.309999,22.600000,21.180000,21.750000,0.0,...,955.409973,955.409973,955.409973,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-21,1445.569946,1453.180054,1439.599976,1441.359985,1.209800e+09,21.549999,21.910000,20.500000,20.820000,0.0,...,951.510010,951.510010,951.510010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.77,NaN,NaN,NaN,NaN
2000-01-24,1441.359985,1454.089966,1395.420044,1401.530029,1.115800e+09,21.430000,24.440001,21.430000,24.070000,0.0,...,956.609985,956.609985,956.609985,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-25,1401.530029,1414.260010,1388.489990,1410.030029,1.073700e+09,23.790001,24.280001,22.870001,23.020000,0.0,...,943.880005,943.880005,943.880005,0.0,NaN,0.91,NaN,NaN,NaN,NaN
2000-01-26,1410.030029,1412.729980,1400.160034,1404.089966,1.117300e+09,22.910000,23.190001,22.450001,23.030001,0.0,...,946.200012,946.200012,946.200012,0.0,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-27,1404.089966,1418.859985,1370.989990,1398.560059,1.129500e+09,22.370001,24.389999,22.030001,23.540001,0.0,...,948.150024,948.150024,948.150024,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-28,1398.560059,1398.560059,1356.199951,1360.160034,1.095800e+09,23.750000,26.540001,23.170000,26.139999,0.0,...,948.210022,948.210022,948.210022,0.0,24.412899,0.00,NaN,71.914247,117.577146,0.033573
2000-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.97,NaN,NaN,NaN,NaN
2000-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.77,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-18,3369.040039,3375.010010,3355.610107,3370.290039,3.746720e+09,14.980000,15.490000,14.530000,14.830000,0.0,...,1175.589966,1167.650024,1172.729980,216363200.0,NaN,2.10,NaN,NaN,NaN,NaN
2020-02-19,3380.389893,3393.520020,3378.830078,3386.149902,3.600150e+09,14.660000,14.740000,14.210000,14.380000,0.0,...,1182.099976,1175.040039,1182.099976,215731000.0,NaN,2.72,NaN,NaN,NaN,NaN
2020-02-20,3380.449951,3389.149902,3341.020020,3373.229980,4.007320e+09,14.540000,17.209999,14.490000,15.560000,0.0,...,1181.239990,1171.089966,1171.089966,229248800.0,NaN,5.70,NaN,NaN,NaN,NaN
2020-02-21,3360.500000,3360.760010,3328.449951,3337.750000,3.899270e+09,17.330000,18.209999,16.190001,17.080000,0.0,...,1171.099976,1157.760010,1164.170044,238290800.0,NaN,6.68,NaN,NaN,NaN,NaN
2020-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.13,NaN,NaN,NaN,NaN
2020-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.13,NaN,NaN,NaN,NaN
2020-02-24,3257.610107,3259.810059,3214.649902,3225.889893,4.842960e+09,22.250000,26.350000,22.000000,25.030001,0.0,...,1134.150024,1113.329956,1120.449951,379225400.0,NaN,6.37,NaN,NaN,NaN,NaN
2020-02-25,3238.939941,3246.989990,3118.770020,3128.209961,5.591510e+09,23.280001,30.250000,22.620001,27.850000,0.0,...,1127.540039,1097.430054,1099.270020,335196000.0,NaN,30.78,NaN,NaN,NaN,NaN
2020-02-26,3139.899902,3182.510010,3108.989990,3116.389893,5.478110e+09,26.629999,29.570000,24.760000,27.559999,0.0,...,1103.689941,1067.709961,1099.410034,392984900.0,NaN,17.15,NaN,NaN,NaN,NaN
2020-02-27,3062.540039,3097.070068,2977.389893,2978.760010,7.058840e+09,32.139999,39.310001,29.370001,39.160000,0.0,...,1082.719971,1045.660034,1059.359985,482892200.0,NaN,26.01,NaN,NaN,NaN,NaN
2020-02-28,2916.899902,2959.719971,2855.840088,2954.219971,8.563850e+09,42.020000,49.480000,39.369999,40.110001,0.0,...,1033.489990,1007.929993,1021.979980,655553200.0,24.443546,40.41,NaN,NaN,NaN,NaN
2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,54.49,NaN,NaN,NaN,NaN
2020-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,34.35,76.532662,NaN,NaN,NaN
2020-03-02,2974.280029,3090.959961,2945.189941,3090.229980,6.376400e+09,38.540001,40.410000,31.500000,33.419998,0.0,...,1047.579956,1002.859985,1027.680054,490681000.0,NaN,24.53,NaN,NaN,NaN,NaN
2020-03-03,3096.459961,3136.719971,2976.629883,3003.370117,6.355940e+09,33.650002,41.060001,24.930000,36.820000,0.0,...,1061.000000,1036.589966,1039.949951,449032400.0,NaN,23.03,NaN,NaN,NaN,NaN
2020-03-04,3045.750000,3130.969971,3034.379883,3130.120117,5.035480e+09,34.439999,35.580002,30.299999,31.990000,0.0,...,1060.119995,1034.290039,1053.729980,381763700.0,NaN,25.47,NaN,NaN,NaN,NaN
2020-03-05,3075.699951,3083.040039,2999.830078,3023.939941,5.575550e+09,33.610001,42.840000,33.540001,39.619999,0.0,...,1060.439941,1029.959961,1036.079956,382979900.0,NaN,19.81,NaN,NaN,NaN,NaN
2020-03-06,2954.199951,2985.929932,2901.540039,2972.370117,6.552140e+09,48.930000,54.389999,40.840000,41.939999,0.0,...,1020.590027,989.070007,994.770020,465581400.0,NaN,25.19,NaN,NaN,NaN,NaN
2020-03-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,27.88,NaN,NaN,NaN,NaN
2020-03-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.65,NaN,NaN,NaN,NaN
2020-03-09,2863.889893,2863.889893,2734.429932,2746.560059,8.423050e+09,41.939999,62.119999,41.939999,54.459999,0.0,...,944.320007,910.979980,914.320007,766019800.0,NaN,52.46,NaN,NaN,NaN,NaN
2020-03-10,2813.479980,2882.590088,2734.000000,2882.229980,7.635960e+09,49.680000,55.660000,43.560001,47.299999,0.0,...,956.390015,897.159973,901.500000,662435100.0,NaN,68.02,NaN,NaN,NaN,NaN
2020-03-11,2825.600098,2825.600098,2707.219971,2741.379883,7.374110e+09,52.240002,55.820000,49.980000,53.900002,0.0,...,924.929993,894.469971,896.159973,528786100.0,NaN,37.69,NaN,NaN,NaN,NaN
2020-03-12,2630.860107,2660.949951,2478.860107,2480.639893,8.829380e+09,61.459999,76.830002,59.910000,75.470001,0.0,...,855.229980,785.450012,788.869995,856804800.0,NaN,34.25,NaN,NaN,NaN,NaN
2020-03-13,2569.989990,2711.330078,2492.370117,2711.020020,8.258670e+09,65.070000,77.570000,55.169998,57.830002,0.0,...,862.320007,790.090027,800.750000,797087400.0,NaN,50.91,NaN,NaN,NaN,NaN
2020-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,47.57,NaN,NaN,NaN,NaN
2020-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,112.93,NaN,NaN,NaN,NaN
2020-03-16,2508.590088,2562.979980,2380.939941,2386.129883,7.781540e+09,57.830002,83.559998,57.830002,82.690002,0.0,...,768.530029,710.469971,755.080017,736759800.0,NaN,56.46,NaN,NaN,NaN,NaN
2020-03-17,2425.659912,2553.929932,2367.040039,2529.189941,8.358500e+09,82.690002,84.830002,70.370003,75.910004,0.0,...,785.140015,729.510010,772.340027,608738100.0,NaN,54.47,NaN,NaN,NaN,NaN
2020-03-18,2436.500000,2453.570068,2280.520020,2398.100098,8.755780e+09,69.370003,85.470001,69.370003,76.449997,0.0,...,759.320007,728.400024,733.929993,536232000.0,NaN,47.95,NaN,NaN,NaN,NaN

In [21]:
df.tail(1000)

,sp500_Open,sp500_High,sp500_Low,sp500_Close,sp500_Volume,vix_Open,vix_High,vix_Low,vix_Close,vix_Volume,...,n100_High,n100_Low,n100_Close,n100_Volume,Overall EMV Tracker,infectious_daily_infect_emv_index,GPR,trade_US Trade Policy Uncertainty,trade_Japanese Trade Policy Uncertainty,trade_Trade Policy EMV Fraction
2017-06-23,2434.649902,2441.399902,2431.110107,2438.300049,5.278330e+09,10.250000,10.690000,9.850000,10.020000,0.0,...,1016.989990,1010.460022,1013.909973,0.0,NaN,0.42,NaN,NaN,NaN,NaN
2017-06-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN,NaN,NaN
2017-06-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.57,NaN,NaN,NaN,NaN
2017-06-26,2443.320068,2450.419922,2437.030029,2439.070068,3.238970e+09,10.130000,10.440000,9.680000,9.900000,0.0,...,1025.260010,1018.929993,1019.380005,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-06-27,2436.340088,2440.149902,2419.379883,2419.379883,3.563910e+09,10.040000,11.310000,9.800000,11.060000,0.0,...,1017.900024,1009.500000,1011.890015,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-06-28,2428.699951,2442.969971,2428.020020,2440.689941,3.500800e+09,11.170000,11.490000,9.760000,10.030000,0.0,...,1013.489990,1001.239990,1009.349976,0.0,12.227028,2.26,NaN,86.858279,144.466755,0.036036
2017-06-29,2442.379883,2442.729980,2405.699951,2419.699951,3.900280e+09,9.790000,15.160000,9.730000,11.440000,0.0,...,1013.299988,988.929993,990.840027,0.0,NaN,0.36,NaN,NaN,NaN,NaN
2017-06-30,2429.199951,2432.709961,2421.649902,2423.409912,3.361590e+09,11.740000,11.850000,10.400000,11.180000,0.0,...,998.330017,985.739990,986.219971,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,91.358265,NaN,NaN,NaN
2017-07-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-03,2431.389893,2439.169922,2428.689941,2429.010010,1.962290e+09,11.070000,11.450000,10.280000,11.220000,0.0,...,998.880005,991.200012,997.989990,0.0,NaN,1.42,NaN,NaN,NaN,NaN
2017-07-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,998.669983,993.219971,994.590027,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-05,2430.780029,2434.899902,2422.050049,2432.540039,3.367220e+09,11.200000,12.030000,10.790000,11.070000,0.0,...,997.130005,991.210022,995.299988,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-06,2423.439941,2424.280029,2407.699951,2409.750000,3.364520e+09,11.200000,13.050000,11.180000,12.540000,0.0,...,995.239990,982.559998,989.760010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-07,2413.520020,2426.919922,2413.520020,2425.179932,2.901330e+09,12.480000,12.570000,10.980000,11.190000,0.0,...,990.330017,986.010010,989.640015,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.72,NaN,NaN,NaN,NaN
2017-07-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.60,NaN,NaN,NaN,NaN
2017-07-10,2424.510010,2432.000000,2422.270020,2427.429932,2.999130e+09,11.260000,11.730000,10.610000,11.110000,0.0,...,996.010010,990.349976,993.640015,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-11,2427.350098,2429.300049,2412.790039,2425.530029,3.106750e+09,10.790000,12.140000,10.680000,10.890000,0.0,...,996.539978,987.940002,988.940002,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-12,2435.750000,2445.760010,2435.750000,2443.250000,3.171620e+09,10.850000,10.850000,10.080000,10.300000,0.0,...,1006.150024,992.119995,1002.890015,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-13,2444.989990,2449.320068,2441.689941,2447.830078,3.067670e+09,10.070000,10.400000,9.900000,9.900000,0.0,...,1010.140015,1003.140015,1006.820007,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-14,2449.159912,2463.540039,2446.689941,2459.270020,2.736640e+09,10.090000,10.140000,9.500000,9.510000,0.0,...,1009.229980,1005.400024,1008.729980,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-17,2459.500000,2462.820068,2457.159912,2459.139893,2.793170e+09,9.770000,10.030000,9.710000,9.820000,0.0,...,1011.820007,1006.010010,1008.979980,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-18,2455.879883,2460.919922,2450.340088,2460.610107,2.962130e+09,9.860000,10.350000,9.660000,9.890000,0.0,...,1009.590027,998.070007,999.909973,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-19,2463.850098,2473.830078,2463.850098,2473.830078,3.059760e+09,9.690000,9.940000,9.580000,9.790000,0.0,...,1008.450012,1001.419983,1008.450012,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-20,2475.560059,2477.620117,2468.429932,2473.449951,3.182780e+09,9.660000,10.280000,9.500000,9.580000,0.0,...,1016.099976,1004.039978,1007.489990,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-21,2467.399902,2472.540039,2465.060059,2472.540039,3.059570e+09,9.520000,9.980000,9.300000,9.360000,0.0,...,1009.479980,991.729980,995.239990,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2017-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-18,3369.040039,3375.010010,3355.610107,3370.290039,3.746720e+09,14.980000,15.490000,14.530000,14.830000,0.0,...,1175.589966,1167.650024,1172.729980,216363200.0,NaN,2.10,NaN,NaN,NaN,NaN
2020-02-19,3380.389893,3393.520020,3378.830078,3386.149902,3.600150e+09,14.660000,14.740000,14.210000,14.380000,0.0,...,1182.099976,1175.040039,1182.099976,215731000.0,NaN,2.72,NaN,NaN,NaN,NaN
2020-02-20,3380.449951,3389.149902,3341.020020,3373.229980,4.007320e+09,14.540000,17.209999,14.490000,15.560000,0.0,...,1181.239990,1171.089966,1171.089966,229248800.0,NaN,5.70,NaN,NaN,NaN,NaN
2020-02-21,3360.500000,3360.760010,3328.449951,3337.750000,3.899270e+09,17.330000,18.209999,16.190001,17.080000,0.0,...,1171.099976,1157.760010,1164.170044,238290800.0,NaN,6.68,NaN,NaN,NaN,NaN
2020-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.13,NaN,NaN,NaN,NaN
2020-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.13,NaN,NaN,NaN,NaN
2020-02-24,3257.610107,3259.810059,3214.649902,3225.889893,4.842960e+09,22.250000,26.350000,22.000000,25.030001,0.0,...,1134.150024,1113.329956,1120.449951,379225400.0,NaN,6.37,NaN,NaN,NaN,NaN
2020-02-25,3238.939941,3246.989990,3118.770020,3128.209961,5.591510e+09,23.280001,30.250000,22.620001,27.850000,0.0,...,1127.540039,1097.430054,1099.270020,335196000.0,NaN,30.78,NaN,NaN,NaN,NaN
2020-02-26,3139.899902,3182.510010,3108.989990,3116.389893,5.478110e+09,26.629999,29.570000,24.760000,27.559999,0.0,...,1103.689941,1067.709961,1099.410034,392984900.0,NaN,17.15,NaN,NaN,NaN,NaN
2020-02-27,3062.540039,3097.070068,2977.389893,2978.760010,7.058840e+09,32.139999,39.310001,29.370001,39.160000,0.0,...,1082.719971,1045.660034,1059.359985,482892200.0,NaN,26.01,NaN,NaN,NaN,NaN
2020-02-28,2916.899902,2959.719971,2855.840088,2954.219971,8.563850e+09,42.020000,49.480000,39.369999,40.110001,0.0,...,1033.489990,1007.929993,1021.979980,655553200.0,24.443546,40.41,NaN,NaN,NaN,NaN
2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,54.49,NaN,NaN,NaN,NaN
2020-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,34.35,76.532662,NaN,NaN,NaN
2020-03-02,2974.280029,3090.959961,2945.189941,3090.229980,6.376400e+09,38.540001,40.410000,31.500000,33.419998,0.0,...,1047.579956,1002.859985,1027.680054,490681000.0,NaN,24.53,NaN,NaN,NaN,NaN
2020-03-03,3096.459961,3136.719971,2976.629883,3003.370117,6.355940e+09,33.650002,41.060001,24.930000,36.820000,0.0,...,1061.000000,1036.589966,1039.949951,449032400.0,NaN,23.03,NaN,NaN,NaN,NaN
2020-03-04,3045.750000,3130.969971,3034.379883,3130.120117,5.035480e+09,34.439999,35.580002,30.299999,31.990000,0.0,...,1060.119995,1034.290039,1053.729980,381763700.0,NaN,25.47,NaN,NaN,NaN,NaN
2020-03-05,3075.699951,3083.040039,2999.830078,3023.939941,5.575550e+09,33.610001,42.840000,33.540001,39.619999,0.0,...,1060.439941,1029.959961,1036.079956,382979900.0,NaN,19.81,NaN,NaN,NaN,NaN
2020-03-06,2954.199951,2985.929932,2901.540039,2972.370117,6.552140e+09,48.930000,54.389999,40.840000,41.939999,0.0,...,1020.590027,989.070007,994.770020,465581400.0,NaN,25.19,NaN,NaN,NaN,NaN
2020-03-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,27.88,NaN,NaN,NaN,NaN
2020-03-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.65,NaN,NaN,NaN,NaN
2020-03-09,2863.889893,2863.889893,2734.429932,2746.560059,8.423050e+09,41.939999,62.119999,41.939999,54.459999,0.0,...,944.320007,910.979980,914.320007,766019800.0,NaN,52.46,NaN,NaN,NaN,NaN
2020-03-10,2813.479980,2882.590088,2734.000000,2882.229980,7.635960e+09,49.680000,55.660000,43.560001,47.299999,0.0,...,956.390015,897.159973,901.500000,662435100.0,NaN,68.02,NaN,NaN,NaN,NaN
2020-03-11,2825.600098,2825.600098,2707.219971,2741.379883,7.374110e+09,52.240002,55.820000,49.980000,53.900002,0.0,...,924.929993,894.469971,896.159973,528786100.0,NaN,37.69,NaN,NaN,NaN,NaN
2020-03-12,2630.860107,2660.949951,2478.860107,2480.639893,8.829380e+09,61.459999,76.830002,59.910000,75.470001,0.0,...,855.229980,785.450012,788.869995,856804800.0,NaN,34.25,NaN,NaN,NaN,NaN
2020-03-13,2569.989990,2711.330078,2492.370117,2711.020020,8.258670e+09,65.070000,77.570000,55.169998,57.830002,0.0,...,862.320007,790.090027,800.750000,797087400.0,NaN,50.91,NaN,NaN,NaN,NaN
2020-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,47.57,NaN,NaN,NaN,NaN
2020-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,112.93,NaN,NaN,NaN,NaN
2020-03-16,2508.590088,2562.979980,2380.939941,2386.129883,7.781540e+09,57.830002,83.559998,57.830002,82.690002,0.0,...,768.530029,710.469971,755.080017,736759800.0,NaN,56.46,NaN,NaN,NaN,NaN
2020-03-17,2425.659912,2553.929932,2367.040039,2529.189941,8.358500e+09,82.690002,84.830002,70.370003,75.910004,0.0,...,785.140015,729.510010,772.340027,608738100.0,NaN,54.47,NaN,NaN,NaN,NaN
2020-03-18,2436.500000,2453.570068,2280.520020,2398.100098,8.755780e+09,69.370003,85.470001,69.370003,76.449997,0.0,...,759.320007,728.400024,733.929993,536232000.0,NaN,47.95,NaN,NaN,NaN,NaN

In [22]:
df.to_csv(r'CompleteIndexes.csv', index = True)