## This notebook merges all indexes using the dates as index and generates one file with daily granularity and one file with weekly granularity

In [1]:
import pandas as pd
from datetime import datetime, timedelta

In [2]:
#Daily
v_sp500 = pd.read_csv('S&P500.csv', parse_dates=True)
v_sp500['Date'] = pd.to_datetime(v_sp500['Date'], infer_datetime_format=True)
v_sp500.index = v_sp500['Date'].values
v_sp500 = v_sp500.loc['2000-01-01':'2020-03-18']
v_sp500 = v_sp500.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_sp500 = v_sp500.add_prefix('sp500_')
v_sp500.tail()

            sp500_Close  sp500_Volume
2020-03-12  2480.639893    8829380000
2020-03-13  2711.020020    8258670000
2020-03-16  2386.129883    7781540000
2020-03-17  2529.189941    8358500000
2020-03-18  2398.100098    8755780000

In [3]:
#Daily
v_vix = pd.read_csv('VIX.csv', parse_dates=True)
v_vix['Date'] = pd.to_datetime(v_vix['Date'], infer_datetime_format=True)
v_vix.index = v_vix['Date'].values
v_vix = v_vix.loc['2000-01-01':'2020-03-18']
v_vix = v_vix.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_vix = v_vix.add_prefix('vix_')
v_vix.head()

            vix_Close  vix_Volume
2000-01-03  24.209999           0
2000-01-04  27.010000           0
2000-01-05  26.410000           0
2000-01-06  25.730000           0
2000-01-07  21.719999           0

In [4]:
#Daily
v_dji = pd.read_csv('^DJI.csv', parse_dates=True)
v_dji['Date'] = pd.to_datetime(v_dji['Date'], infer_datetime_format=True)
v_dji.index = v_dji['Date'].values
v_dji = v_dji.loc['2000-01-01':'2020-03-18']
v_dji = v_dji.drop(['Date', 'Adj Close', 'High', 'Low', 'Open', 'High', 'Low', 'Open'], axis=1)
v_dji = v_dji.add_prefix('dji_')
v_dji.head()

               dji_Close  dji_Volume
2000-01-03  11357.509766   169750000
2000-01-04  10997.929688   178420000
2000-01-05  11122.650391   203190000
2000-01-06  11253.259766   176550000
2000-01-07  11522.559570   184900000

In [5]:
#Daily
v_ndx = pd.read_csv('^NDX.csv', parse_dates=True)
v_ndx['Date'] = pd.to_datetime(v_ndx['Date'], infer_datetime_format=True)
v_ndx.index = v_ndx['Date'].values
v_ndx = v_ndx.loc['2000-01-01':'2020-03-18']
v_ndx = v_ndx.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_ndx = v_ndx.add_prefix('ndx_')
v_ndx.head()

              ndx_Close  ndx_Volume
2000-01-03  3790.550049  1510070000
2000-01-04  3546.199951  1511840000
2000-01-05  3507.310059  1735670000
2000-01-06  3340.810059  1598320000
2000-01-07  3529.600098  1634930000

In [6]:
#Daily
v_n225 = pd.read_csv('N225.csv', parse_dates=True)
v_n225['Date'] = pd.to_datetime(v_n225['Date'], infer_datetime_format=True)
v_n225.index = v_n225['Date'].values
v_n225 = v_n225.loc['2000-01-01':'2020-03-18']
v_n225 = v_n225.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_n225 = v_n225.add_prefix('n255_')
v_n225.head()

              n255_Close  n255_Volume
2000-01-04  19002.859375          0.0
2000-01-05  18542.550781          0.0
2000-01-06  18168.269531          0.0
2000-01-07  18193.410156          0.0
2000-01-10           NaN          NaN

In [7]:
#Daily
v_ftse = pd.read_csv('CompleteFTSE.csv', parse_dates=True)
v_ftse['Date'] = pd.to_datetime(v_ftse['Date'], infer_datetime_format=True)
v_ftse.index = v_ftse['Date'].values
v_ftse = v_ftse.loc['2000-01-01':'2020-03-18']
v_ftse = v_ftse.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_ftse = v_ftse.add_prefix('ftse_')
v_ftse.head()

             ftse_Close  ftse_Volume
2000-01-03          NaN          NaN
2000-01-04  6665.899902  633449000.0
2000-01-05  6535.899902  670234000.0
2000-01-06  6447.200195  785532000.0
2000-01-07  6504.799805  888306000.0

In [8]:
#Daily
v_hsi = pd.read_csv('^HSI.csv', parse_dates=True)
v_hsi['Date'] = pd.to_datetime(v_hsi['Date'], infer_datetime_format=True)
v_hsi.index = v_hsi['Date'].values
v_hsi = v_hsi.loc['2000-01-01':'2020-03-18']
v_hsi = v_hsi.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_hsi = v_hsi.add_prefix('hsi_')
v_hsi.head()

               hsi_Close  hsi_Volume
2000-01-03  17369.630859         0.0
2000-01-04  17072.820313         0.0
2000-01-05  15846.719727         0.0
2000-01-06  15153.230469         0.0
2000-01-07  15405.629883         0.0

In [9]:
#Daily
v_n100 = pd.read_csv('^N100.csv', parse_dates=True)
v_n100['Date'] = pd.to_datetime(v_n100['Date'], infer_datetime_format=True)
v_n100.index = v_n100['Date'].values
v_n100 = v_n100.loc['2000-01-01':'2020-03-18']
v_n100 = v_n100.drop(['Date', 'Adj Close', 'High', 'Low', 'Open'], axis=1)
v_n100 = v_n100.add_prefix('n100_')
v_n100.head()

            n100_Close  n100_Volume
2000-01-03  996.770020          0.0
2000-01-04  955.969971          0.0
2000-01-05  930.260010          0.0
2000-01-06  922.460022          0.0
2000-01-07  943.880005          0.0

In [10]:
#Monthly
v_emv =  pd.read_excel('EMV_Data.xlsx') 
Date = v_emv.apply(lambda x: datetime(int(x['Year']),int(x['Month']),28), axis=1)
v_emv['Date'] = Date
v_emv['Date'] = pd.to_datetime(v_emv['Date'], infer_datetime_format=True)
v_emv.index = v_emv['Date'].values
v_emv = v_emv.loc['2000-01-01':'2020-03-18']
v_emv = v_emv[['Overall EMV Tracker']]
v_emv.head()

            Overall EMV Tracker
2000-01-28            24.412899
2000-02-28            19.913437
2000-03-28            26.104673
2000-04-28            43.429073
2000-05-28            34.308361

In [11]:
#Daily
v_infectious = pd.read_csv('All_Infectious_EMV_Data.csv')
Date = v_infectious.apply(lambda x: datetime(int(x['year']),int(x['month']), int(x['day'])), axis=1)
v_infectious['Date'] = Date
v_infectious['Date'] = pd.to_datetime(v_infectious['Date'], infer_datetime_format=True)
v_infectious.index = v_infectious['Date'].values
v_infectious = v_infectious.loc['2000-01-01':'2020-03-18']
v_infectious = v_infectious.drop(['Date', 'day', 'month', 'year'], axis=1)
v_infectious = v_infectious.add_prefix('infectious_')
v_infectious.head()

            infectious_daily_infect_emv_index
2000-01-01                               1.05
2000-01-02                               2.62
2000-01-03                               0.00
2000-01-04                               0.99
2000-01-05                               0.00

In [12]:
#Quarterly - might not use
v_financial_stress = pd.read_excel('Financial_Stress.xlsx')
Date = v_financial_stress.apply(lambda x: datetime(int(x['year']),int(x['quarter'])*3, 28), axis=1)
v_financial_stress['Date'] = Date
v_financial_stress['Date'] = pd.to_datetime(v_financial_stress['Date'], infer_datetime_format=True)
v_financial_stress.index = v_financial_stress['Date'].values
v_financial_stress = v_financial_stress.loc['2000-01-01':'2020-03-18']
v_financial_stress = v_financial_stress.drop(['date', 'Date', 'quarter', 'year'], axis=1)
v_financial_stress = v_financial_stress.add_prefix('financial_')
v_financial_stress.head()

            financial_indicator
2000-03-28           101.588292
2000-06-28           101.361929
2000-09-28           100.836200
2000-12-28           101.377272
2001-03-28           102.227537

In [13]:
#Monthly
v_gpr = pd.read_excel('gpr_web_latest.xlsx')
v_gpr['Date'] = pd.to_datetime(v_gpr['Date'], infer_datetime_format=True)
v_gpr.index = v_gpr['Date'].values
v_gpr = v_gpr.loc['2000-01-01':'2020-03-18']
v_gpr = v_gpr[['GPR']]
v_gpr.head()

                  GPR
2000-01-01  40.634806
2000-02-01  34.391162
2000-03-01  54.098793
2000-04-01  35.769024
2000-05-01  34.094887

In [14]:
#Monthly
v_trade_uncertainty = pd.read_excel('Trade_Uncertainty_Data.xlsx') 
Date = v_trade_uncertainty.apply(lambda x: datetime(int(x['Year']),int(x['Month']),28), axis=1)
v_trade_uncertainty['Date'] = Date
v_trade_uncertainty['Date'] = pd.to_datetime(v_trade_uncertainty['Date'], infer_datetime_format=True)
v_trade_uncertainty.index = v_trade_uncertainty['Date'].values
v_trade_uncertainty = v_trade_uncertainty.loc['2000-01-01':'2020-03-18']
v_trade_uncertainty = v_trade_uncertainty.drop(['Date', 'Year', 'Month'], axis=1)
v_trade_uncertainty = v_trade_uncertainty.add_prefix('trade_')
v_trade_uncertainty.head()

,trade_US Trade Policy Uncertainty,trade_Japanese Trade Policy Uncertainty,trade_Trade Policy EMV Fraction
2000-01-28,71.914247,117.577146,0.033573
2000-02-28,50.352413,58.499365,0.026471
2000-03-28,88.179754,31.808480,0.028139
2000-04-28,82.574216,54.061788,0.033755
2000-05-28,245.009584,73.961645,0.025000

In [15]:
df = pd.concat([v_sp500, v_vix, v_dji, v_ndx, v_n225, v_ftse, v_hsi, v_n100, v_emv, v_infectious, v_gpr, v_trade_uncertainty], axis=1, join='outer')

In [16]:
at_least_one_value_missing = df.apply(lambda x: (len(x)-x.count())>=1, axis=1)

In [17]:
at_least_one_value_missing.value_counts()

True    7383
dtype: int64

In [18]:
df

,sp500_Close,sp500_Volume,vix_Close,vix_Volume,dji_Close,dji_Volume,ndx_Close,ndx_Volume,n255_Close,n255_Volume,...,hsi_Close,hsi_Volume,n100_Close,n100_Volume,Overall EMV Tracker,infectious_daily_infect_emv_index,GPR,trade_US Trade Policy Uncertainty,trade_Japanese Trade Policy Uncertainty,trade_Trade Policy EMV Fraction
2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.05,40.634806,NaN,NaN,NaN
2000-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.62,NaN,NaN,NaN,NaN
2000-01-03,1455.219971,9.318000e+08,24.209999,0.0,11357.509766,169750000.0,3790.550049,1.510070e+09,NaN,NaN,...,17369.630859,0.000000e+00,996.770020,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-04,1399.420044,1.009000e+09,27.010000,0.0,10997.929688,178420000.0,3546.199951,1.511840e+09,19002.859375,0.0,...,17072.820313,0.000000e+00,955.969971,0.0,NaN,0.99,NaN,NaN,NaN,NaN
2000-01-05,1402.109985,1.085500e+09,26.410000,0.0,11122.650391,203190000.0,3507.310059,1.735670e+09,18542.550781,0.0,...,15846.719727,0.000000e+00,930.260010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-06,1403.449951,1.092300e+09,25.730000,0.0,11253.259766,176550000.0,3340.810059,1.598320e+09,18168.269531,0.0,...,15153.230469,0.000000e+00,922.460022,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-07,1441.469971,1.225200e+09,21.719999,0.0,11522.559570,184900000.0,3529.600098,1.634930e+09,18193.410156,0.0,...,15405.629883,0.000000e+00,943.880005,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-10,1457.599976,1.064800e+09,21.709999,0.0,11572.200195,168180000.0,3717.409912,1.691710e+09,NaN,NaN,...,15848.150391,0.000000e+00,960.219971,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-11,1438.560059,1.014000e+09,22.500000,0.0,11511.080078,177300000.0,3544.350098,1.694460e+09,18850.919922,0.0,...,15862.099609,0.000000e+00,954.059998,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-12,1432.250000,9.746000e+08,22.840000,0.0,11551.099609,194060000.0,3478.139893,1.525900e+09,18677.419922,0.0,...,15714.200195,0.000000e+00,946.830017,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-13,1449.680054,1.030400e+09,21.709999,0.0,11582.429688,174910000.0,3612.080078,1.476970e+09,18833.289063,0.0,...,15633.959961,0.000000e+00,951.820007,0.0,NaN,0.72,NaN,NaN,NaN,NaN
2000-01-14,1465.150024,1.085900e+09,19.660000,0.0,11722.980469,266830000.0,3704.739990,1.656630e+09,18956.550781,0.0,...,15542.230469,0.000000e+00,973.859985,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19437.230469,0.0,...,15574.559570,0.000000e+00,979.960022,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-18,1455.140015,1.056700e+09,21.500000,0.0,11560.719727,200220000.0,3757.780029,1.585230e+09,19196.570313,0.0,...,15789.200195,0.000000e+00,952.590027,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-19,1455.900024,1.087800e+09,21.719999,0.0,11489.360352,193090000.0,3790.889893,1.652210e+09,18897.750000,0.0,...,15275.339844,0.000000e+00,951.260010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-20,1445.569946,1.100700e+09,21.750000,0.0,11351.299805,191230000.0,3841.739990,1.851300e+09,19008.009766,0.0,...,15215.309570,0.000000e+00,955.409973,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-21,1441.359985,1.209800e+09,20.820000,0.0,11251.709961,205840000.0,3849.959961,1.923680e+09,18878.089844,0.0,...,15108.410156,0.000000e+00,951.510010,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.77,NaN,NaN,NaN,NaN
2000-01-24,1401.530029,1.115800e+09,24.070000,0.0,11008.169922,202740000.0,3660.959961,1.989050e+09,19056.710938,0.0,...,15167.549805,0.000000e+00,956.609985,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-25,1410.030029,1.073700e+09,23.020000,0.0,11029.889648,209230000.0,3759.110107,1.743630e+09,18895.529297,0.0,...,15103.040039,0.000000e+00,943.880005,0.0,NaN,0.91,NaN,NaN,NaN,NaN
2000-01-26,1404.089966,1.117300e+09,23.030001,0.0,11032.990234,188840000.0,3621.209961,1.717000e+09,19111.189453,0.0,...,15427.719727,0.000000e+00,946.200012,0.0,NaN,0.78,NaN,NaN,NaN,NaN
2000-01-27,1398.560059,1.129500e+09,23.540001,0.0,11028.019531,194280000.0,3593.149902,1.798460e+09,19209.720703,0.0,...,15917.809570,0.000000e+00,948.150024,0.0,NaN,0.00,NaN,NaN,NaN,NaN
2000-01-28,1360.160034,1.095800e+09,26.139999,0.0,10738.870117,183090000.0,3446.129883,1.616370e+09,19434.779297,0.0,...,16185.940430,0.000000e+00,948.210022,0.0,24.412899,0.00,NaN,71.914247,117.577146,0.033573
2000-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.97,NaN,NaN,NaN,NaN
2000-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.77,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-18,3370.290039,3.746720e+09,14.830000,0.0,29232.189453,256600000.0,9629.799805,2.273460e+09,23193.800781,59500.0,...,27530.199219,1.592221e+09,1172.729980,216363200.0,NaN,2.10,NaN,NaN,NaN,NaN
2020-02-19,3386.149902,3.600150e+09,14.380000,0.0,29348.029297,240640000.0,9718.730469,2.462530e+09,23400.699219,61600.0,...,27655.810547,1.471538e+09,1182.099976,215731000.0,NaN,2.72,NaN,NaN,NaN,NaN
2020-02-20,3373.229980,4.007320e+09,15.560000,0.0,29219.980469,287780000.0,9627.830078,2.735610e+09,23479.150391,63300.0,...,27609.160156,1.582073e+09,1171.089966,229248800.0,NaN,5.70,NaN,NaN,NaN,NaN
2020-02-21,3337.750000,3.899270e+09,17.080000,0.0,28992.410156,311210000.0,9446.690430,2.743010e+09,23386.740234,62100.0,...,27308.810547,1.773613e+09,1164.170044,238290800.0,NaN,6.68,NaN,NaN,NaN,NaN
2020-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.13,NaN,NaN,NaN,NaN
2020-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.13,NaN,NaN,NaN,NaN
2020-02-24,3225.889893,4.842960e+09,25.030001,0.0,27960.800781,452580000.0,9079.629883,3.177000e+09,NaN,NaN,...,26820.880859,2.044657e+09,1120.449951,379225400.0,NaN,6.37,NaN,NaN,NaN,NaN
2020-02-25,3128.209961,5.591510e+09,27.850000,0.0,27081.359375,513270000.0,8834.870117,3.583400e+09,22605.410156,105800.0,...,26893.230469,1.924043e+09,1099.270020,335196000.0,NaN,30.78,NaN,NaN,NaN,NaN
2020-02-26,3116.389893,5.478110e+09,27.559999,0.0,26957.589844,472450000.0,8873.759766,3.567830e+09,22426.189453,99300.0,...,26696.490234,0.000000e+00,1099.410034,392984900.0,NaN,17.15,NaN,NaN,NaN,NaN
2020-02-27,2978.760010,7.058840e+09,39.160000,0.0,25766.640625,664980000.0,8436.669922,1.086700e+08,21948.230469,106200.0,...,26778.619141,2.110370e+09,1059.359985,482892200.0,NaN,26.01,NaN,NaN,NaN,NaN
2020-02-28,2954.219971,8.563850e+09,40.110001,0.0,25409.359375,915990000.0,8461.830078,5.301170e+09,21142.960938,148500.0,...,26129.929688,3.191426e+09,1021.979980,655553200.0,24.443546,40.41,NaN,NaN,NaN,NaN
2020-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,54.49,NaN,NaN,NaN,NaN
2020-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,34.35,76.532662,NaN,NaN,NaN
2020-03-02,3090.229980,6.376400e+09,33.419998,0.0,26703.320313,637200000.0,8877.980469,4.232760e+09,21344.080078,123700.0,...,26291.679688,2.201536e+09,1027.680054,490681000.0,NaN,24.53,NaN,NaN,NaN,NaN
2020-03-03,3003.370117,6.355940e+09,36.820000,0.0,25917.410156,647080000.0,8594.490234,4.336700e+09,21082.730469,105300.0,...,26284.820313,2.136295e+09,1039.949951,449032400.0,NaN,23.03,NaN,NaN,NaN,NaN
2020-03-04,3130.120117,5.035480e+09,31.990000,0.0,27090.859375,457590000.0,8949.280273,3.602870e+09,21100.060547,94600.0,...,26222.070313,1.957062e+09,1053.729980,381763700.0,NaN,25.47,NaN,NaN,NaN,NaN
2020-03-05,3023.939941,5.575550e+09,39.619999,0.0,26121.279297,477370000.0,8671.660156,3.748090e+09,21329.119141,85700.0,...,26767.869141,2.522843e+09,1036.079956,382979900.0,NaN,19.81,NaN,NaN,NaN,NaN
2020-03-06,2972.370117,6.552140e+09,41.939999,0.0,25864.779297,599780000.0,8530.339844,4.279850e+09,20749.750000,111700.0,...,26146.669922,2.646519e+09,994.770020,465581400.0,NaN,25.19,NaN,NaN,NaN,NaN
2020-03-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,27.88,NaN,NaN,NaN,NaN
2020-03-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.65,NaN,NaN,NaN,NaN
2020-03-09,2746.560059,8.423050e+09,54.459999,0.0,23851.019531,750430000.0,7948.029785,4.530350e+09,19698.759766,170300.0,...,25040.460938,4.677892e+09,914.320007,766019800.0,NaN,52.46,NaN,NaN,NaN,NaN
2020-03-10,2882.229980,7.635960e+09,47.299999,0.0,25018.160156,654860000.0,8372.269531,4.431930e+09,19867.119141,164700.0,...,25392.509766,3.225661e+09,901.500000,662435100.0,NaN,68.02,NaN,NaN,NaN,NaN
2020-03-11,2741.379883,7.374110e+09,53.900002,0.0,23553.220703,663960000.0,8006.120117,4.273890e+09,19416.060547,129200.0,...,25231.609375,2.627626e+09,896.159973,528786100.0,NaN,37.69,NaN,NaN,NaN,NaN
2020-03-12,2480.639893,8.829380e+09,75.470001,0.0,21200.619141,908260000.0,7263.649902,5.066530e+09,18559.630859,164600.0,...,24309.070313,3.748928e+09,788.869995,856804800.0,NaN,34.25,NaN,NaN,NaN,NaN
2020-03-13,2711.020020,8.258670e+09,57.830002,0.0,23185.619141,843080000.0,7995.259766,4.685890e+09,17431.050781,233400.0,...,24032.910156,5.495156e+09,800.750000,797087400.0,NaN,50.91,NaN,NaN,NaN,NaN
2020-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,47.57,NaN,NaN,NaN,NaN
2020-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,112.93,NaN,NaN,NaN,NaN
2020-03-16,2386.129883,7.781540e+09,82.690002,0.0,20188.519531,770130000.0,7020.379883,4.594360e+09,17002.039063,158100.0,...,23063.570313,4.067029e+09,755.080017,736759800.0,NaN,56.46,NaN,NaN,NaN,NaN
2020-03-17,2529.189941,8.358500e+09,75.910004,0.0,21237.380859,793060000.0,7473.950195,4.900000e+09,17011.529297,198800.0,...,23263.730469,3.637974e+09,772.340027,608738100.0,NaN,54.47,NaN,NaN,NaN,NaN
2020-03-18,2398.100098,8.755780e+09,76.449997,0.0,19898.919922,871360000.0,7175.180176,4.890820e+09,16726.550781,177200.0,...,NaN,NaN,733.929993,536232000.0,NaN,47.95,NaN,NaN,NaN,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7383 entries, 2000-01-01 to 2020-03-18
Data columns (total 22 columns):
sp500_Close                                5084 non-null float64
sp500_Volume                               5084 non-null float64
vix_Close                                  5084 non-null float64
vix_Volume                                 5084 non-null float64
dji_Close                                  5084 non-null float64
dji_Volume                                 5084 non-null float64
ndx_Close                                  5084 non-null float64
ndx_Volume                                 5084 non-null float64
n255_Close                                 4952 non-null float64
n255_Volume                                4952 non-null float64
ftse_Close                                 4869 non-null float64
ftse_Volume                                4869 non-null float64
hsi_Close                                  4977 non-null float64
hsi_Volume                                 4977 non-null float64
n100_Close                                 5166 non-null float64
n100_Volume                                5166 non-null float64
Overall EMV Tracker                        242 non-null float64
infectious_daily_infect_emv_index          7383 non-null float64
GPR                                        243 non-null float64
trade_US Trade Policy Uncertainty          235 non-null float64
trade_Japanese Trade Policy Uncertainty    235 non-null float64
trade_Trade Policy EMV Fraction            235 non-null float64
dtypes: float64(22)
memory usage: 1.3 MB

In [20]:
df.to_csv(r'CompleteIndexes.csv', index = True)

In [21]:
# Generating weekly sampled dataset
df_friday = datetime(2000,1,7)

df_weekly = pd.DataFrame(columns = df.columns)
df_out_weekly = pd.DataFrame(columns = df.columns)


while df_friday <= df.tail(1).index:
    df_weekly = df_weekly.append(df.loc[df_friday])
    df_friday+=timedelta(days=7)

In [22]:
df_weekly.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1054 entries, 2000-01-07 to 2020-03-13
Data columns (total 22 columns):
sp500_Close                                1021 non-null float64
sp500_Volume                               1021 non-null float64
vix_Close                                  1021 non-null float64
vix_Volume                                 1021 non-null float64
dji_Close                                  1021 non-null float64
dji_Volume                                 1021 non-null float64
ndx_Close                                  1021 non-null float64
ndx_Volume                                 1021 non-null float64
n255_Close                                 1009 non-null float64
n255_Volume                                1009 non-null float64
ftse_Close                                 978 non-null float64
ftse_Volume                                978 non-null float64
hsi_Close                                  993 non-null float64
hsi_Volume                                 993 non-null float64
n100_Close                                 1024 non-null float64
n100_Volume                                1024 non-null float64
Overall EMV Tracker                        36 non-null float64
infectious_daily_infect_emv_index          1054 non-null float64
GPR                                        35 non-null float64
trade_US Trade Policy Uncertainty          35 non-null float64
trade_Japanese Trade Policy Uncertainty    35 non-null float64
trade_Trade Policy EMV Fraction            35 non-null float64
dtypes: float64(22)
memory usage: 189.4 KB

In [23]:
df_weekly.to_csv(r'CompleteWeeklyIndexes.csv', index = True)